Repository wasseobi/seobi-backend, pull requests merged in 2025-06, with the labels that each got.

#52 💚 Introduce pr test
  .github/workflows/main_seobi-backend.yml
  app/models/schedule.py
  config.py
Labels: enhancement

#62 🐛 Fix session close
  .github/workflows/main_seobi-backend.yml
  app/services/session_service.py
Labels: bug

#68 Issue template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintenance.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#65 Test/add dao full test
  .github/workflows/main_seobi-backend.yml
  app/dao/insight_article_dao.py
  app/dao/message_dao.py
  app/dao/schedule_dao.py
  app/services/insight_article_service.py
  app/services/reports/get_report_service.py
  app/services/schedule_service.py
  tests/db_setup.py
  tests/test_dao/test_insight_article_dao.py
  tests/test_dao/test_schedule_dao.py
Labels: enhancement

#72 🐛 Fix undefined reference
  app/services/interest_service.py
Labels: bug

#77 대화 후 처리 워크플로우 개선
  app/langgraph/cleanup/nodes/analyze_conversation.py
  app/langgraph/cleanup/nodes/generate_tasks.py
  app/routes/session.py
  app/schemas/auto_task_schema.py
  app/services/auto_task_service.py
  app/services/cleanup_service.py
  app/services/session_service.py
  app/utils/prompt/cleanup_prompts.py
Labels: enhancement

#80 [Test] add redis test server
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/main_seobi-backend.yml
Labels: enhancement

#81 Final 세션 내 히스토리, 장기기억
  app/dao/user_dao.py
  app/langgraph/agent/agent_state.py
  app/langgraph/agent/executor.py
  app/langgraph/agent/graph.py
  app/langgraph/agent/nodes/call_model.py
  app/langgraph/agent/nodes/cleanup_node.py
  app/langgraph/agent/nodes/model_node.py
  app/langgraph/agent/nodes/summarize_node.py
  app/langgraph/agent/nodes/tool_node.py
  app/langgraph/tools.py
  app/routes/session.py
  app/services/message_service.py
  app/services/user_service.py
  app/utils/agent_state_store.py
  app/utils/app_config.py
  app/utils/message/converter.py
  app/utils/message/formatter.py
  app/utils/message/message_context.py
  app/utils/message/processor.py
  app/utils/openai_client.py
  app/utils/prompt/agent_prompt.py
  app/utils/prompt/service_prompts.py
  config.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#85 🐛 유저 세션 못가져오는 문제 해결
  app/routes/session.py
Labels: bug

#91 🧑‍💻 Add override option for load_dotenv
  app/__init__.py
Labels: enhancement

#92 GOOGLE CLIENT ID 문제
  .github/workflows/main_seobi-backend.yml
  app/utils/app_config.py
Labels: bug

#95 Report/plus 주간, 월간 리포트 추가, 데일리 리포트 오류 수정
  app/dao/insight_article_dao.py
  app/dao/interest_dao.py
  app/dao/report_dao.py
  app/dao/schedule_dao.py
  app/routes/__init__.py
  app/routes/debug/report.py
  app/routes/report.py
  app/services/reports/daily/generate_daily_report.py
  app/services/reports/daily/get_daily_report.py
  app/services/reports/daily/summarize_daily_report.py
  app/services/reports/generate_report.py
  app/services/reports/generate_report_service.py
  app/services/reports/monthly/generate_monthly_report.py
  app/services/reports/monthly/get_monthly_report.py
  app/services/reports/monthly/summarize_monthly_report.py
  app/services/reports/report_service.py
  app/services/reports/summarize_report.py
  app/services/reports/summarize_report_service.py
  app/services/reports/weekly/generate_weekly_report.py
  app/services/reports/weekly/get_weekly_report.py
  app/services/reports/weekly/summarize_weekly_report.py
  app/services/schedule_service.py
  app/utils/prompt/monthly_report_prompts.py
  app/utils/prompt/reports/daily_report_prompts.py
  app/utils/prompt/reports/monthly_report_prompts.py
  app/utils/prompt/reports/weekly_report_prompts.py
  app/utils/time.py
Labels: enhancement

#108 Revert "🐛 Fix session close error"
  app/routes/session.py
Labels: bug

#110 Hotfix/closed session messages
  app/services/message_service.py
Labels: enhancement

#114 Hotfix/improve openai policy
  app/langgraph/cleanup/edges/cleanup_edges.py
  app/langgraph/cleanup/nodes/generate_tasks.py
  app/routes/session.py
Labels: bug

#115 Hotfix/daily report
  app/routes/debug/report.py
Labels: bug

#119 Feat/auto task api
  app/__init__.py
  app/routes/auto_task.py
  app/routes/debug/auto_task.py
  app/schemas/auto_task_schema.py
  app/services/auto_task_service.py
Labels: enhancement

#123 🐛 Fix remaining time for auto task
  app/services/auto_task_service.py
Labels: bug

#129 ⚡️ Introduce async for session close
  app/routes/session.py
Labels: enhancement

#131 Refac/remove session summary
  app/routes/session.py
  app/services/session_service.py
Labels: enhancement

#140 Hotfix/improve session summary
  app/services/session_service.py
  app/utils/prompt/service_prompts.py
Labels: bug, enhancement

#147 Feat/introduce mcp langgraph
  app/langgraph/agent/executor.py
  app/langgraph/agent/graph.py
  app/langgraph/agent/nodes/call_model.py
  app/langgraph/agent/nodes/model_node.py
  app/langgraph/agent/nodes/tool_node.py
  app/services/message_service.py
  app/utils/prompt/agent_prompt.py
  pyproject.toml
  requirements.txt
Labels: enhancement
